language: ruby
script: bundle exec rake
sudo: false
rvm:
  - 1.9.3
  - 2.1.*
  - 2.2.*
  - 2.3.0
  #- ruby-head
gemfile:
  - Gemfile
  - Gemfile.fluentd.v0.12
  - Gemfile.fluentd.v0.10
before_install:
  - gem update bundler
